### ISSUE TITLE
Is it compatible with the latest HNS protocol?

### ISSUE THREAD

**Issue by gg2001** [handshake-org/hnsd#37]
> ⚠️ Currently, hnsd is not compatible with the latest, Handshake p2p network protocol. We are exploring a potential rewrite of the entire codebase. Please watch this repo for development updates.

Has this been fixed yet?

**Comment by pinheadmz** [comment]
Yes, https://github.com/handshake-org/hnsd/issues/33 has been closed and the four pull requests required to refactor hnsd for mainnet usage have been merged. Master branch can be compiled and run to resolve mainnet HNS right now. We haven't removed the warning yet because we are still working on clearnet p2p and peer discovery #35 and #36. Until these are merged, hnsd will only connect to the short list of hard-coded seed nodes. So there is a potential centralization issue there, but otherwise hnsd is useable.

We could use a lot of help reviewing, even the four PR's that were already merged. If you don't have time or can't read C, then please beta-test and report any issues (especially memory leaks if you have the ability to run valgrind). Even once the last two PRs are merged, we'll probably just *change* the warning to indicate that hnsd is in beta and still might need further improvements before prime time.

I'm going to close this issue for now because it is just a question and not an issue, but feel free to add more comments.
