### ISSUE TITLE
Inconsistent response around ttl expiry

### ISSUE THREAD

**Issue by RevCBH** [handshake-org/hnsd#57]
With hnsd running locally:  `dig @127.0.0.1 -t txt f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu`

The domain has one TXT record with a TTL of 5 seconds.

The dig command usually produces a result with that TXT record in the answer section. Occasionally, as the ttl expires, it produces a result with no answers and just an authority section.

I've copied hnsd logs for two consecutive executions of that dig command, the first succeeding, the second failing:

```
rs: query
rs:   id=15530
rs:   labels=4
rs:   name=f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu.
rs:   type=16
rs:   class=1
rs:   edns=1
rs:   dnssec=0
rs:   tld=johnxu
rs:   addr=127.0.0.1:56465
rs_worker: request 191: f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu.
rs: received answer for: f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu.
rs:   rcode: 0
rs:   havedata: 1
rs:   nxdomain: 0
rs:   secure: 0
rs:   bogus: 1
rs:   why_bogus: validation failure <f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu. TXT IN>: key for validation johnxu. is marked as invalid because of a previous validation failure <f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu. TXT IN>: no DNSSEC records from 44.231.6.183 for DS johnxu. while building chain of trust
rs: query
rs:   id=10958
rs:   labels=4
rs:   name=f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu.
rs:   type=16
rs:   class=1
rs:   edns=1
rs:   dnssec=0
rs:   tld=johnxu
rs:   addr=127.0.0.1:40859
rs_worker: request 192: f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu.
rs: received answer for: f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu.
rs:   rcode: 3
rs:   havedata: 0
rs:   nxdomain: 1
rs:   secure: 0
rs:   bogus: 1
rs:   why_bogus: validation failure <f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu. TXT IN>: key for validation johnxu. is marked as invalid because of a previous validation failure <f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu. TXT IN>: no DNSSEC records from 44.231.6.183 for DS johnxu. while building chain of trust
```

**Comment by RevCBH** [comment]
cc: @turbomaze

**Comment by pinheadmz** [comment]
Interesting, I can reproduce this by making the same request repeatedly and yeah sometimes right at TTL 0 it returns the SOA from the nameserver instead:

```
;; AUTHORITY SECTION:
johnxu.                 3424    IN      SOA     ns1.johnxu. dns-admin.namebase.io. 2021030503 10800 3600 604800 3600
```

The recursive resolve in hnsd is from unbound - and so I'm pretty sure the cache and the TTL are handled there as well. I wonder if this is caused by a race condition when you query right at the moment that cache is being flushed or something.

**Comment by RevCBH** [comment]
It's weird because I don't get that behavior for a similarly configured domain `b61723f7-2693-44ec-831e-bab015fad535._auth.tonydustin`

**Comment by pinheadmz** [comment]
could this be an issue with the nameserver? Or does the TLD have multiple NS listed? are they all in sync?

**Comment by RevCBH** [comment]
They're running on the same NS, but I'll double check the onchain records and the config in NS

**Comment by pinheadmz** [comment]
ok I dont think its the nameserver, because I can dig it directly `dig @44.231.6.183 ` and always get a response, even with `watch --interval 0.5` So maybe something to do with unbound cache then

**Comment by RevCBH** [comment]
Ok. I'l, uh, _dig_ into that then 👍

**Comment by RevCBH** [comment]
I'm still not 100% clear on what's happening, but I was able to work around the issue locally by creating a libunbound config file with an upstream provider set to the ip for the ns1.johnxu nameserver.

It explains the NXDOMAIN because the request was going to whatever the upstream was (or the icann root). Is this expected behavior?

**Comment by pinheadmz** [comment]
I went down the rabbit hole on this one today and got a lot of help from #dns channel on IRC. I'm still not _exactly_ why the behavior is inconsistent but I did learn some things. Ultimately I think this `_auth` scheme may need to be tightened up. There may some things we can try in `hnsd` to accommodate, but then it's not guaranteed to work with every resolver all the time.

1) qname minimization

See [unbound.conf docs](https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/). What it means is that instead of asking an authority for the entire string `abc.def.ghi.jkl`, you just ask one label at a time, expecting an NS to some other authority where you ask the next label:`jkl` first, then `ghi.jkl` then `def.ghi.jkl` etc

This is set to true in hnsd:

https://github.com/handshake-org/hnsd/blob/c4d0a9ffd823cd605c7ba8358982157071d64137/src/rs.c#L218

One thing to look at with the `_auth` scheme is you have `NXDOMAIN` "holes" in the chain of delegation:

`johnxu`: Exists in HNS root zone with an `NS` record
`jee.johnxu`: `NXDOMAIN`
`_auth.jee.johnxu`: `NXDOMAIN`
`f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu`: `NOERROR` (because there's a `TXT` if you just ask for it)

This can break recursive resolution depending on what software you use and how it's configured. This brings us to...

2) harden-below-nxdomain

See [unbound.conf docs](https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/). I'm not going to act like I know exactly what this means, but it is the source of a [related issue](https://github.com/NLnetLabs/unbound/issues/162) and basically what happens is related to the qname-minimization thing:

We ask for `jee.johnxu` and get `NXDOMAIN` -- therefore we don't even bother asking for any subdomains lower than `jee.johnxu`! The `NXDOMAIN` from this second-level domain is cached and _returned_ by unbound for all remaining queries. You can actually see this [when the missing txt thing happens](https://pastebin.com/raw/YwWmbFc7) notice how the `NXDOMAIN` answer has a TTL of `3588`, thus implying that that record has _actually been in the cache for 12 seconds already_.

harden-below-nxdomain is not set in `hnsd`, but could be.

At this point, the real 🤔  isn't so much why does this request fail when the TTL hits `0` but more like "why did this ever work the other 99% of the time?"

To investigate this further I'd like to:

- Try these requests with wireshark and confirm my suspicion, that an `NXDOMAIN` from early in the recursion process is being cached and unbound doesn't even bother requesting the next two labels.

- Try patching `hnsd` with qname-minimize `false` and harden-below-nxdomain `no` and try these requests again, see if they ever fail.

**Comment by turbomaze** [comment]
That's fantastic thanks so much for investigating. Good next steps for us to investigate

**Comment by buffrr** [comment]
@pinheadmz is right about this you can't have NXDOMAIN holes here. It should be NODATA all the way. Unbound is very permissive about this other recursive resolvers will likely answer NXDOMAIN for anything underneath `jee.johnxu` since it technically doesn't exist.

> One thing to look at with the _auth scheme is you have NXDOMAIN "holes" in the chain of delegation:

> johnxu: Exists in HNS root zone with an NS record
> jee.johnxu: NXDOMAIN
> _auth.jee.johnxu: NXDOMAIN
> f44ca263-6f26-410d-a08a-ac3bb0f7c480._auth.jee.johnxu: NOERROR (because there's a TXT if you just ask for it)
